name: matookelog
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  path: ^1.8.4
  fl_chart: ^1.1.1
  google_fonts: ^4.0.4
  intl: ^0.18.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
